/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;

@JsonTypeInfo(use=Id.MINIMAL_CLASS, include=As.PROPERTY, property="kind")
@JsonSubTypes({@Type(Account.Configured.class), @Type(Account.Unconfigured.class)})
public abstract class Account {

  public static class Configured extends Account {
    public String addr;
    public String color;
    public String displayName;
    public Integer id;
    public String profileImage;
  }

  public static class Unconfigured extends Account {
    public Integer id;
  }

}