/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

/**
 * cheaper version of fullchat, omits: - contacts - contact_ids - fresh_message_counter - ephemeral_timer - self_in_group - was_seen_recently - can_send
 *
 * used when you only need the basic metadata of a chat like type, name, profile picture
 */
public class BasicChat {
  public Boolean archived;
  public Integer chatType;
  public String color;
  public Integer id;
  public Boolean isContactRequest;
  public Boolean isDeviceChat;
  public Boolean isMuted;
  /**
   * True if the chat is protected.
   *
   * UI should display a green checkmark in the chat title, in the chat profile title and in the chatlist item if chat protection is enabled. UI should also display a green checkmark in the contact profile if 1:1 chat with this contact exists and is protected.
   */
  public Boolean isProtected;
  public Boolean isProtectionBroken;
  public Boolean isSelfTalk;
  public Boolean isUnpromoted;
  public String name;
  public String profileImage;
}