/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;

@JsonTypeInfo(use=Id.MINIMAL_CLASS, include=As.PROPERTY, property="kind")
@JsonSubTypes({@Type(ChatListItemFetchResult.ChatListItem.class), @Type(ChatListItemFetchResult.ArchiveLink.class), @Type(ChatListItemFetchResult.Error.class)})
public abstract class ChatListItemFetchResult {

  public static class ChatListItem extends ChatListItemFetchResult {
    public String avatarPath;
    public String color;
    /* contact id if this is a dm chat (for view profile entry in context menu) */
    public Integer dmChatContact;
    public Integer freshMessageCounter;
    public Integer id;
    public Boolean isArchived;
    /* true when chat is a broadcastlist */
    public Boolean isBroadcast;
    public Boolean isContactRequest;
    public Boolean isDeviceTalk;
    public Boolean isGroup;
    public Boolean isMuted;
    public Boolean isPinned;
    public Boolean isProtected;
    public Boolean isSelfInGroup;
    public Boolean isSelfTalk;
    public Boolean isSendingLocation;
    public Integer lastMessageId;
    public Viewtype lastMessageType;
    public Integer lastUpdated;
    public String name;
    /* showing preview if last chat message is image */
    public String summaryPreviewImage;
    public Integer summaryStatus;
    public String summaryText1;
    public String summaryText2;
    public Boolean wasSeenRecently;
  }

  public static class ArchiveLink extends ChatListItemFetchResult {
    public Integer freshMessageCounter;
  }

  public static class Error extends ChatListItemFetchResult {
    public String error;
    public Integer id;
  }

}