/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class Contact {
  public String address;
  public String authName;
  public String color;
  public String displayName;
  public Integer id;
  public Boolean isBlocked;
  /* If the contact is a bot. */
  public Boolean isBot;
  /**
   * True if the contact profile title should have a green checkmark.
   *
   * This indicates whether 1:1 chat has a green checkmark or will have a green checkmark if created.
   */
  public Boolean isProfileVerified;
  /**
   * True if the contact can be added to verified groups.
   *
   * If this is true UI should display green checkmark after the contact name in contact list items, in chat member list items and in profiles if no chat with the contact exist.
   */
  public Boolean isVerified;
  /* the contact's last seen timestamp */
  public Integer lastSeen;
  public String name;
  public String nameAndAddr;
  public String profileImage;
  public String status;
  /**
   * The ID of the contact that verified this contact.
   *
   * If this is present, display a green checkmark and "Introduced by ..." string followed by the verifier contact name and address in the contact profile.
   */
  public Integer verifierId;
  public Boolean wasSeenRecently;
}