/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;

@JsonTypeInfo(use=Id.MINIMAL_CLASS, include=As.PROPERTY, property="kind")
@JsonSubTypes({@Type(EphemeralTimer.Disabled.class), @Type(EphemeralTimer.Enabled.class)})
public abstract class EphemeralTimer {

/* Timer is disabled. */
  public static class Disabled extends EphemeralTimer {
  }

/* Timer is enabled. */
  public static class Enabled extends EphemeralTimer {
    /**
     * Timer duration in seconds.
     *
     * The value cannot be 0.
     */
    public Integer duration;
  }

}