/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class Location {
  public Float accuracy;
  public Integer chatId;
  public Integer contactId;
  public Boolean isIndependent;
  public Float latitude;
  public Integer locationId;
  public Float longitude;
  public String marker;
  public Integer msgId;
  public Integer timestamp;
}