/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class MessageNotificationInfo {
  public Integer accountId;
  public Integer chatId;
  public String chatName;
  public String chatProfileImage;
  public Integer id;
  public String image;
  public String imageMimeType;
  /* also known as summary_text1 */
  public String summaryPrefix;
  /* also known as summary_text2 */
  public String summaryText;
}