/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class MessageInfo {
  public EphemeralTimer ephemeralTimer;
  /* When message is ephemeral this contains the timestamp of the message expiry */
  public Integer ephemeralTimestamp;
  public String error;
  public String hopInfo;
  public String rawtext;
  public String rfc724Mid;
  public java.util.List<String> serverUrls;
}