/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;

@JsonTypeInfo(use=Id.MINIMAL_CLASS, include=As.PROPERTY, property="kind")
@JsonSubTypes({@Type(MessageQuote.JustText.class), @Type(MessageQuote.WithMessage.class)})
public abstract class MessageQuote {

  public static class JustText extends MessageQuote {
    public String text;
  }

  public static class WithMessage extends MessageQuote {
    public String authorDisplayColor;
    public String authorDisplayName;
    @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
    public String image;
    public Boolean isForwarded;
    public Integer messageId;
    @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
    public String overrideSenderName;
    public String text;
    public Viewtype viewType;
  }

}