/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class MessageSearchResult {
  public String authorColor;
  public Integer authorId;
  /* if sender name if overridden it will show it as ~alias */
  public String authorName;
  public String authorProfileImage;
  public String chatColor;
  public String chatName;
  public String chatProfileImage;
  public Integer chatType;
  public Integer id;
  public Boolean isChatArchived;
  public Boolean isChatContactRequest;
  public Boolean isChatProtected;
  public String message;
  public Integer timestamp;
}