/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class MessageData {
  public String file;
  public String html;
  public Pair<Float, Float> location;
  public String overrideSenderName;
  public Integer quotedMessageId;
  public String text;
  public Viewtype viewtype;
}