/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;

@JsonTypeInfo(use=Id.MINIMAL_CLASS, include=As.PROPERTY, property="kind")
@JsonSubTypes({@Type(MuteDuration.NotMuted.class), @Type(MuteDuration.Forever.class), @Type(MuteDuration.Until.class)})
public abstract class MuteDuration {

  public static class NotMuted extends MuteDuration {
  }

  public static class Forever extends MuteDuration {
  }

  public static class Until extends MuteDuration {
    public Integer duration;
  }

}