/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;

@JsonTypeInfo(use=Id.MINIMAL_CLASS, include=As.PROPERTY, property="kind")
@JsonSubTypes({@Type(Qr.AskVerifyContact.class), @Type(Qr.AskVerifyGroup.class), @Type(Qr.FprOk.class), @Type(Qr.FprMismatch.class), @Type(Qr.FprWithoutAddr.class), @Type(Qr.Account.class), @Type(Qr.Backup.class), @Type(Qr.WebrtcInstance.class), @Type(Qr.Addr.class), @Type(Qr.Url.class), @Type(Qr.Text.class), @Type(Qr.WithdrawVerifyContact.class), @Type(Qr.WithdrawVerifyGroup.class), @Type(Qr.ReviveVerifyContact.class), @Type(Qr.ReviveVerifyGroup.class), @Type(Qr.Login.class)})
public abstract class Qr {

  public static class AskVerifyContact extends Qr {
    public String authcode;
    public Integer contact_id;
    public String fingerprint;
    public String invitenumber;
  }

  public static class AskVerifyGroup extends Qr {
    public String authcode;
    public Integer contact_id;
    public String fingerprint;
    public String grpid;
    public String grpname;
    public String invitenumber;
  }

  public static class FprOk extends Qr {
    public Integer contact_id;
  }

  public static class FprMismatch extends Qr {
    public Integer contact_id;
  }

  public static class FprWithoutAddr extends Qr {
    public String fingerprint;
  }

  public static class Account extends Qr {
    public String domain;
  }

  public static class Backup extends Qr {
    public String ticket;
  }

  public static class WebrtcInstance extends Qr {
    public String domain;
    public String instance_pattern;
  }

  public static class Addr extends Qr {
    public Integer contact_id;
    public String draft;
  }

  public static class Url extends Qr {
    public String url;
  }

  public static class Text extends Qr {
    public String text;
  }

  public static class WithdrawVerifyContact extends Qr {
    public String authcode;
    public Integer contact_id;
    public String fingerprint;
    public String invitenumber;
  }

  public static class WithdrawVerifyGroup extends Qr {
    public String authcode;
    public Integer contact_id;
    public String fingerprint;
    public String grpid;
    public String grpname;
    public String invitenumber;
  }

  public static class ReviveVerifyContact extends Qr {
    public String authcode;
    public Integer contact_id;
    public String fingerprint;
    public String invitenumber;
  }

  public static class ReviveVerifyGroup extends Qr {
    public String authcode;
    public Integer contact_id;
    public String fingerprint;
    public String grpid;
    public String grpname;
    public String invitenumber;
  }

  public static class Login extends Qr {
    public String address;
  }

}