/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class VcardContact {
  /* Email address. */
  public String addr;
  /* Contact color as hex string. */
  public String color;
  /* The contact's name, or the email address if no name was given. */
  public String displayName;
  /* Public PGP key in Base64. */
  public String key;
  /* Profile image in Base64. */
  public String profileImage;
  /* Last update timestamp. */
  public Integer timestamp;
}