/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class WebxdcMessageInfo {
  /* if the Webxdc represents a document, then this is the name of the document */
  public String document;
  /**
   * App icon file name. Defaults to an standard icon if nothing is set in the manifest.
   *
   * To get the file, use dc_msg_get_webxdc_blob(). (not yet in jsonrpc, use rust api or cffi for it)
   *
   * App icons should should be square, the implementations will add round corners etc. as needed.
   */
  public String icon;
  /* True if full internet access should be granted to the app. */
  public Boolean internetAccess;
  /**
   * The name of the app.
   *
   * Defaults to the filename if not set in the manifest.
   */
  public String name;
  /* URL where the source code of the Webxdc and other information can be found; defaults to an empty string. Implementations may offer an menu or a button to open this URL. */
  public String sourceCodeUrl;
  /* short string describing the state of the app, sth. as "2 votes", "Highscore: 123", can be changed by the apps */
  public String summary;
}