blank_issues_enabled: false
contact_links:
  - name: Feature requests
    url: https://support.delta.chat/c/features/6
    about: Please discuss feature requests on our Community forum.
  - name: General Questions
    url: https://support.delta.chat/c/help/5
    about: Please ask general Questions on our Community forum.
