/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

/** Version information of a single source of a client, eg. "gplay" or "fdroid". */
public class AppSource {
  /** Where to download that version. Security note: consumers need to verify themselves that downloaded app files are valid before installing them. */
  public String downloadUrl;
  /** Always increasing version number. */
  public Integer versionInteger;
  /** Any version string. */
  public String versionString;
}