/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

/**
 * cheaper version of fullchat, omits: - contacts - contact_ids - fresh_message_counter - ephemeral_timer - self_in_group - was_seen_recently - can_send
 * <p>
 * used when you only need the basic metadata of a chat like type, name, profile picture
 */
public class BasicChat {
  public Boolean archived;
  public ChatType chatType;
  public String color;
  public Integer id;
  public Boolean isContactRequest;
  public Boolean isDeviceChat;
  /**
   * True if the chat is encrypted. This means that all messages in the chat are encrypted, and all contacts in the chat are "key-contacts", i.e. identified by the PGP key fingerprint.
   * <p>
   * False if the chat is unencrypted. This means that all messages in the chat are unencrypted, and all contacts in the chat are "address-contacts", i.e. identified by the email address. The UI should mark this chat e.g. with a mail-letter icon.
   * <p>
   * Unencrypted groups are called "ad-hoc groups" and the user can't add/remove members, create a QR invite code, or set an avatar. These options should therefore be disabled in the UI.
   * <p>
   * Note that it can happen that an encrypted chat contains unencrypted messages that were received in core <= v1.159.* and vice versa.
   * <p>
   * See also `is_key_contact` on `Contact`.
   */
  public Boolean isEncrypted;
  public Boolean isMuted;
  public Boolean isSelfTalk;
  public Boolean isUnpromoted;
  public String name;
  public Boolean pinned;
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String profileImage;
}