/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class CallInfo {
  /**
   * SDP offer.
   * <p>
   * Can be used to manually answer the call even if incoming call event was missed.
   */
  public String sdpOffer;
  /**
   * Call state.
   * <p>
   * For example, if the call is accepted, active, cancelled, declined etc.
   */
  public CallState state;
}