/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class Contact {
  public String address;
  public String authName;
  public String color;
  public String displayName;
  /**
   * Is encryption available for this contact.
   * <p>
   * This can only be true for key-contacts. However, it is possible to have a key-contact for which encryption is not available because we don't have a key yet, e.g. if we just scanned the fingerprint from a QR code.
   */
  public Boolean e2eeAvail;
  public ContactFreshness freshness;
  public Integer id;
  public Boolean isBlocked;
  /** If the contact is a bot. */
  public Boolean isBot;
  /** Is the contact a key contact. */
  public Boolean isKeyContact;
  /** the contact's last seen timestamp */
  public Integer lastSeen;
  public String name;
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String profileImage;
  public String status;
}