/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public enum ContactFreshness {
  /** Contact shall not be highlighted. */
  Normal,

  /** Contact was seen recently. */
  RecentlySeen,

  /** Contact was not seen for a long time. */
  Old,
}