/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public enum EnteredCertificateChecks {
  /** `Automatic` means strict certificate checks, unless a legacy-domain override disables them. */
  automatic,

  /** Ensure that TLS certificate is valid for the server hostname. */
  strict,

  /** Accept certificates that are expired, self-signed or otherwise not valid for the server hostname. */
  acceptInvalidCertificates,
}