/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

/**
 * Login parameters entered by the user.
 * <p>
 * Usually it will be enough to only set `addr` and `password`, and all the other settings will be autoconfigured.
 */
public class EnteredLoginParam {
  /** Email address. */
  public String addr;
  /** TLS options: whether to allow invalid certificates and/or invalid hostnames. Default: Automatic */
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public EnteredCertificateChecks certificateChecks;
  /** Imap server port. */
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public Integer imapPort;
  /** Imap socket security. */
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public Socket imapSecurity;
  /** Imap server hostname or IP address. */
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String imapServer;
  /** Imap username. */
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String imapUser;
  /** If true, login via OAUTH2 (not recommended anymore). Default: false */
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public Boolean oauth2;
  /** Password. */
  public String password;
  /**
   * SMTP Password.
   * <p>
   * Only needs to be specified if different than IMAP password.
   */
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String smtpPassword;
  /** SMTP server port. */
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public Integer smtpPort;
  /** SMTP socket security. */
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public Socket smtpSecurity;
  /** SMTP server hostname or IP address. */
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String smtpServer;
  /** SMTP username. */
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String smtpUser;
}