/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class MessageInfo {
  public EphemeralTimer ephemeralTimer;
  /** When message is ephemeral this contains the timestamp of the message expiry */
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public Integer ephemeralTimestamp;
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String error;
  public String hopInfo;
  public String rfc724Mid;
  public java.util.List<String> serverUrls;
}