/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class MessageNotificationInfo {
  public Integer accountId;
  public Integer chatId;
  public String chatName;
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String chatProfileImage;
  public Integer id;
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String image;
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String imageMimeType;
  /** also known as summary_text1 */
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String summaryPrefix;
  /** also known as summary_text2 */
  public String summaryText;
}