/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;

@JsonTypeInfo(use=Id.NAME, include=As.PROPERTY, property="kind")
@JsonSubTypes({@Type(value = MessageListItem.Message.class, name="Message"), @Type(value = MessageListItem.DayMarker.class, name="DayMarker")})
public abstract class MessageListItem {

  public static class Message extends MessageListItem {
    public Integer msg_id;
  }

/** Day marker, separating messages that correspond to different days according to local time. */
  public static class DayMarker extends MessageListItem {
    /** Marker timestamp, for day markers, in unix milliseconds */
    public Integer timestamp;
  }

}