/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class MessageSearchResult {
  public String authorColor;
  public Integer authorId;
  /** if sender name if overridden it will show it as ~alias */
  public String authorName;
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String authorProfileImage;
  public String chatColor;
  public Integer chatId;
  public String chatName;
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String chatProfileImage;
  public ChatType chatType;
  public Integer id;
  public Boolean isChatArchived;
  public Boolean isChatContactRequest;
  public String message;
  public Integer timestamp;
}