/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public enum NotifyState {
  /** Not subscribed to push notifications. */
  NotConnected,

  /** Subscribed to heartbeat push notifications. */
  Heartbeat,

  /** Subscribed to push notifications for new messages. */
  Connected,
}