/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

/** Structure representing all reactions to a particular message. */
public class Reactions {
  /** Unique reactions and their count, sorted in descending order. */
  public java.util.List<Reaction> reactions;
  /** Map from a contact to it's reaction to message. There is only a single reaction per contact, but this contains a list of reactions for historical reasons. */
  public java.util.Map<String, java.util.List<String>> reactionsByContact;
}