/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

/** Structure representing all reactions to a particular message. */
public class Reactions {
  /** Unique reactions and their count, sorted in descending order. */
  public java.util.List<Reaction> reactions;
  /** Map from a contact to it's reaction to message. */
  public java.util.Map<String, java.util.List<String>> reactionsByContact;
}