/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

/** A single reaction emoji. */
public class Reaction {
  /** Emoji frequency. */
  public Integer count;
  /** Emoji. */
  public String emoji;
  /** True if we reacted with this emoji. */
  public Boolean isFromSelf;
}