/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public enum SecurejoinUiPath {
  /** The UI path is unknown, or the user didn't open the QR code screen at all. */
  Unknown,

  /** The user directly clicked on the QR icon in the main screen */
  QrIcon,

  /** The user first clicked on the `+` button in the main screen, and then on "New Contact" */
  NewContact,

  /** The user scanned a join QR code when creating a new profile from Instant Onborading Screen */
  // FIXME: need to be added in core
  // InstantOnboarding,
}
