/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public enum Socket {
  /** Unspecified socket security, select automatically. */
  automatic,

  /** TLS connection. */
  ssl,

  /** STARTTLS connection. */
  starttls,

  /** No TLS, plaintext connection. */
  plain,
}