/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public enum SystemMessageType {
  Unknown,
  GroupNameChanged,
  GroupDescriptionChanged,
  GroupImageChanged,
  MemberAddedToGroup,
  MemberRemovedFromGroup,
  AutocryptSetupMessage,
  SecurejoinMessage,
  LocationStreamingEnabled,
  LocationOnly,
  InvalidUnencryptedMail,
  ChatE2ee,
  ChatProtectionEnabled,
  ChatProtectionDisabled,
  WebxdcStatusUpdate,
  CallAccepted,
  CallEnded,
  MessagePinned,
  MessageUnpinned,

  /** Single chats info message telling that SecureJoin has started and the user should wait for it to complete. */
  SecurejoinWait,

  /** Single chats info message telling that SecureJoin is still running, but the user may already send messages. */
  SecurejoinWaitTimeout,

  /** Chat ephemeral message timer is changed. */
  EphemeralTimerChanged,

  /** Self-sent-message that contains only json used for multi-device-sync; if possible, we attach that to other messages as for locations. */
  MultiDeviceSync,

  /** Webxdc info added with `info` set in `send_webxdc_status_update()`. */
  WebxdcInfoMessage,

  /** This message contains a users iroh node address. */
  IrohNodeAddr,
}