/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class Transport {
  /** Whether this transport is set to 'unpublished'. See `set_transport_unpublished` / `setTransportUnpublished` for details. */
  public Boolean isUnpublished;
  /** The login data entered by the user. */
  public EnteredLoginParam param;
}