/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public enum Viewtype {
  Unknown,

  /** Text message. */
  Text,

  /** Image message. If the image is an animated GIF, the type `Viewtype.Gif` should be used. */
  Image,

  /** Animated GIF message. */
  Gif,

  /**
   * Message containing a sticker, similar to image. NB: When sending, the message viewtype may be changed to `Image` by some heuristics like checking for transparent pixels. Use `Message::force_sticker()` to disable them.
   * <p>
   * If possible, the ui should display the image without borders in a transparent way. A click on a sticker will offer to install the sticker set in some future.
   */
  Sticker,

  /** Message containing an Audio file. */
  Audio,

  /** A voice message that was directly recorded by the user. For all other audio messages, the type `Viewtype.Audio` should be used. */
  Voice,

  /** Video messages. */
  Video,

  /** Message containing any file, eg. a PDF. */
  File,

  /** Message is a call. */
  Call,

  /** Message is an webxdc instance. */
  Webxdc,

  /** Message containing shared contacts represented as a vCard (virtual contact file) with email addresses and possibly other fields. Use `parse_vcard()` to retrieve them. */
  Vcard,
}