/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class WebxdcMessageInfo {
  /** if the Webxdc represents a document, then this is the name of the document */
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String document;
  /**
   * App icon file name. Defaults to an standard icon if nothing is set in the manifest.
   * <p>
   * To get the file, use dc_msg_get_webxdc_blob(). (not yet in jsonrpc, use rust api or cffi for it)
   * <p>
   * App icons should should be square, the implementations will add round corners etc. as needed.
   */
  public String icon;
  /** True if full internet access should be granted to the app. */
  public Boolean internetAccess;
  /**
   * The name of the app.
   * <p>
   * Defaults to the filename if not set in the manifest.
   */
  public String name;
  /** Address to be used for `window.webxdc.selfAddr` in JS land. */
  public String selfAddr;
  /** Milliseconds to wait before calling `sendUpdate()` again since the last call. Should be exposed to `window.sendUpdateInterval` in JS land. */
  public Integer sendUpdateInterval;
  /** Maximum number of bytes accepted for a serialized update object. Should be exposed to `window.sendUpdateMaxSize` in JS land. */
  public Integer sendUpdateMaxSize;
  /** URL where the source code of the Webxdc and other information can be found; defaults to an empty string. Implementations may offer an menu or a button to open this URL. */
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String sourceCodeUrl;
  /** short string describing the state of the app, sth. as "2 votes", "Highscore: 123", can be changed by the apps */
  @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SET)
  public String summary;
}