name: Compile Check

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  compile:
    name: Compile Delta Chat Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 17
          distribution: 'temurin'

      - uses: android-actions/setup-android@40fd30fb8d7440372e1316f5d1809ec01dcd3699 # v4.0.1

      - name: Compile Java
        run: ./gradlew --no-daemon compileGplayDebugJavaWithJavac
